### ISSUE TITLE
Alternative version without Okta?

### ISSUE THREAD

**Issue by cmar0ck** [rdegges/chatapp#1]
Very cool app :)
Only downside (at least to me) is that it builds on Okta,
is there an alternative way of authentication or could the app run without any authentication at all (for e.g. anyone who has the link to the room can join)?

**Comment by rdegges** [comment]
Totally! You can plug in your own authentication (or no authentication at all!) -- I like using Okta because it doesn't require a backend and is really simple, but you can use whatever you want.

If you want to run it without any authentication, just rip out the Okta bits and you'll be good to go, no major modification needed.
